SES_USER_NAME: "AKIAIK7YC5UWBLPCCM6A"
SES_PASSWORD: "AoIem+Y3D1LOBXRu0ahjxeZBZ1GGr/SODJv12MfVIT/G"
GOOGLE_CLIENT_ID: "1085379230550-7hsj7elj1thqatg5kf1mhpbisbd7e565.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET: "-VSNvJG-lV6pxq5f9y8eXcLz"